apiVersion: v1
kind: Service
metadata:
  name: cranecloud-docs
  namespace: cranecloud-prod
  labels:
    app: docs
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: cranecloud-docs