apiVersion: v1
kind: Service
metadata:
  name: mira
  namespace: cranecloud
  labels:
    app: mira
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: mira