apiVersion: v1
kind: Service
metadata:
  name: cranecloud-frontend
  namespace: cranecloud-prod
  labels:
    app: cranecloud-frontend
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: react-frontend
  selector:
    app: cranecloud-frontend