apiVersion: v1
kind: Service
metadata:
  name: cranecloud-backend
  namespace: cranecloud
  labels:
    app: backend
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: cranecloud-backend