apiVersion: apps/v1
kind: Deployment
metadata:
  name: cranecloud-backend
  namespace: cranecloud
spec:
  replicas: 3
  minReadySeconds: 15
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: cranecloud-backend
  template:
    metadata:
      labels:
        app: cranecloud-backend
    spec:
      containers:
        - name: cranecloud-backend
          image: ckwagaba/crane-cloud-backend:f4b3eedb73b054463f77a3ef5eb9c797e5f0a48c
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: flask-api
          envFrom:
            - configMapRef:
                name: backend-variables
    
