apiVersion: apps/v1
kind: Deployment
metadata:
  name: cranecloud-docs
  namespace: cranecloud
spec:
  replicas: 2
  minReadySeconds: 15
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: cranecloud-docs
  template:
    metadata:
      labels:
        app: cranecloud-docs
    spec:
      containers:
        - name: cranecloud-backend
          image: asiimwe/docs
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: cranecloud-docs